/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package handong.edu.csee.pp1;

public class Main {
    public static void main(String[] args) {
        new WordManager().start();
    }
}
